#!/bin/sh
# Dynamically enable Nginx HTTPS if TLS certs exist in the data volume.
# Users place tls.crt + tls.key in /app/data/ssl/ (same volume as other data).
set -e

NGINX_CONF="/etc/nginx/conf.d/default.conf"
NGINX_SSL_DIR="/etc/nginx/ssl"
SSL_SRC="/app/data/ssl"
mkdir -p "$NGINX_SSL_DIR"

if [ -f "$SSL_SRC/tls.crt" ] && [ -f "$SSL_SRC/tls.key" ]; then
    cp "$SSL_SRC/tls.crt" "$SSL_SRC/tls.key" "$NGINX_SSL_DIR/"
    echo "[https] /app/data/ssl/ 中检测到 TLS 证书，启用 HTTPS"
    cat > "$NGINX_CONF" <<'EOF'
# Auto-generated by docker-entrypoint.sh (HTTPS enabled)

server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/ssl/tls.crt;
    ssl_certificate_key /etc/nginx/ssl/tls.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
    gzip_min_length 1000;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 300s;
        proxy_connect_timeout 60s;
    }
}
EOF
else
    echo "[https] 未检测到 TLS 证书，使用 HTTP-only 配置"
    echo "[https] 如需 HTTPS，将 tls.crt + tls.key 放入 /app/data/ssl/ 即可"
fi